version: "3.6"

services:
  web:
    build: nginx
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ".:/app"

    links:
      - php
    networks:
       default:
           aliases:
               - rubberducky.test
               - www.rubberducky.test


  php:
    build: php-fpm
    volumes:
      - ".:/app"
    networks: [default]

  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - ".:/app"


networks:
    default: ~
